/*
 * @Author: ran
 * @Date: 2022-02-20 15:24:05
 * @LastEditTime: 2022-02-20 15:25:08
 * @LastEditors: Please set LastEditors
 */
export default [
    {
      fontFamily: 'Microsoft YaHei',
      fontFamilyCN: '微软雅黑',
      fileName: 'msyh.ttc',
      url: 'https://s3.com/fonts/msyh.ttc',
    },
    {
      fontFamily: 'Microsoft YaHei Bold',
      fontFamilyCN: '微软雅黑-粗',
      fileName: 'msyhbd.ttc',
      url: 'https://s3.com/fonts/msyhbd.ttc',
    },
    {
      fontFamily: 'SentyZHAO',
      fontFamilyCN: '新蒂赵孟頫体',
      fileName:'SentyZHAO.ttf',
      url: 'https://s3.com/fonts/SentyZHAO.ttf',
    },
    {
      fontFamily: 'SentyTEA',
      fontFamilyCN: '汉仪新蒂下午茶体',
      fileName:'SentyTEA.ttf',
      url: 'https://s3.com/fonts/SentyTEA.ttf',
    },
    {
      fontFamily: 'SentySnowMountain',
      fontFamilyCN: '汉仪新蒂雪山体',
      fileName:'SentySnowMountain.ttf',
      url: 'https://s3.com/fonts/SentySnowMountain.ttf',
    },
    {
      fontFamily: 'SentyMARUKO',
      fontFamilyCN: '汉仪新蒂小丸子体',
      fileName:'SentyMARUKO.ttf',
      url: 'https://s3.com/fonts/SentyMARUKO.ttf',
    },
    {
      fontFamily: 'SentyGoldenBell',
      fontFamilyCN: '汉仪新蒂金钟体',
      fileName:'SentyGoldenBell.ttf',
      url: 'https://s3.com/fonts/SentyGoldenBell.ttf',
    },
    {
      fontFamily: 'SentyCreamPuff',
      fontFamilyCN: '汉仪新蒂泡芙体',
      fileName:'SentyCreamPuff.ttf',
      url: 'https://s3.com/fonts/SentyCreamPuff.ttf',
    },
    {
      fontFamily: 'SentyCHALKoriginal',
      fontFamilyCN: '汉仪新蒂黑板报底字',
      fileName:'SentyCHALKoriginal.ttf',
      url: 'https://s3.com/fonts/SentyCHALKoriginal.ttf',
    },
    {
      fontFamily: 'NotoSansHans-Regular',
      fontFamilyCN: '思源黑体-Regular',
      fileName:'NotoSansHans-Regular.otf',
      url: 'https://s3.com/fonts/NotoSansHans-Regular.otf',
    },
    {
      fontFamily: 'NotoSansHans-Black',
      fontFamilyCN: '思源黑体-Black',
      fileName:'NotoSansHans-Black.otf',
      url: 'https://s3.com/fonts/NotoSansHans-Black.otf',
    },
    {
      fontFamily: 'NotoSansHans-Medium',
      fontFamilyCN: '思源黑体-Medium',
      fileName:'NotoSansHans-Medium.otf',
      url: 'https://s3.com/fonts/NotoSansHans-Medium.otf',
    },
    {
      fontFamily: 'NotoSansHans-Light',
      fontFamilyCN: '思源黑体-Light',
      fileName:'NotoSansHans-Light.otf',
      url: 'https://s3.com/fonts/NotoSansHans-Light.otf',
    },
    {
      fontFamily: 'NotoSansHans-DemiLight',
      fontFamilyCN: '思源黑体-DemiLight',
      fileName:'NotoSansHans-DemiLight.otf',
      url: 'https://s3.com/fonts/NotoSansHans-DemiLight.otf',
    },
    {
      fontFamily: 'NotoSansHans-Thin-Windows',
      fontFamilyCN: '思源黑体-Thin-Windows',
      fileName:'NotoSansHans-Thin-Windows.otf',
      url: 'https://s3.com/fonts/NotoSansHans-Thin-Windows.otf',
    },
    {
      fontFamily: 'NotoSansHans-Bold',
      fontFamilyCN: '思源黑体-Bold',
      fileName:'NotoSansHans-Bold.otf',
      url: 'https://s3.com/fonts/NotoSansHans-Bold.otf',
    },
    {
      fontFamily: 'FZLanTingKanHeiS-R-GB',
      fontFamilyCN: '方正兰亭刊黑简体',
      url: 'https://s3.com/fonts/5ac3c6bf.TTF',
      fileName:'方正兰亭刊黑简体.TTF',
    },
    {
      fontFamily: 'FZZhengHeiS-EB-GB',
      fontFamilyCN: '方正正大黑简体',
      url: 'https://s3.com/fonts/4280629a.TTF',
      fileName:'方正正大黑简体.TTF',
    },
    {
      fontFamily: 'DFWaWaSC-W5',
      fontFamilyCN: '娃娃体',
      url: 'https://s3.com/fonts/DFWaWaSC-W5.ttf',
    },
    {
      fontFamily: 'FZZongYi-M05S',
      fontFamilyCN: '方正综艺简体',
      url: 'https://s3.com/fonts/FZZYJW.ttf',
    },
    {
      fontFamily: 'FZZhiYi-M12S',
      fontFamilyCN: '方正稚艺简体',
      url: 'https://s3.com/fonts/FZZHYJW.ttf',
    },
    {
      fontFamily: 'FZZhongDengXian-Z07S',
      fontFamilyCN: '方正中等线简体',
      url: 'https://s3.com/fonts/FZZDXJW.ttf',
    },
    {
      fontFamily: 'FZZhanBiHei-M22S',
      fontFamilyCN: '方正毡笔黑简体',
      url: 'https://s3.com/fonts/FZZBHJW.ttf',
    },
    {
      fontFamily: 'FZYouXian-Z09S',
      fontFamilyCN: '方正幼线简体',
      url: 'https://s3.com/fonts/FZYXJW.ttf',
    },
    {
      fontFamily: 'FZYiHei-M20S',
      fontFamilyCN: '方正艺黑简体',
      url: 'https://s3.com/fonts/FZYHJW.ttf',
    },
    {
      fontFamily: 'FZYunDongHeiS-M-GB',
      fontFamilyCN: '方正韵动中黑简体',
      url: 'https://s3.com/fonts/FZYDZHJW.ttf',
    },
    {
      fontFamily: 'FZCuYuan-M03S',
      fontFamilyCN: '方正粗圆简体',
      url: 'https://s3.com/fonts/FZY4JW.ttf',
    },
    {
      fontFamily: 'FZZhunYuan-M02S',
      fontFamilyCN: '方正准圆简体',
      url: 'https://s3.com/fonts/FZY3JW.ttf',
    },
    {
      fontFamily: 'FZXiaoZhuanTi-S13T',
      fontFamilyCN: '方正小篆体',
      url: 'https://s3.com/fonts/FZXZTFW.ttf',
    },
    {
      fontFamily: 'FZXiQian-M15S',
      fontFamilyCN: '方正细倩简体',
      url: 'https://s3.com/fonts/FZXQJW.ttf',
    },
    {
      fontFamily: ' FZXiHeiI-Z08S',
      fontFamilyCN: '方正细黑一简体',
      url: 'https://s3.com/fonts/FZXH1JW.ttf',
    },
    {
      fontFamily: 'FZXiDengXian-Z06S',
      fontFamilyCN: '方正细等线简体',
      url: 'https://s3.com/fonts/FZXDXJW.ttf',
    },
    {
      fontFamily: 'FZXiaoBiaoSong-B05S',
      fontFamilyCN: '方正小标宋简体',
      url: 'https://s3.com/fonts/FZXBSJW.ttf',
    },
    {
      fontFamily: 'FZWeiBei-S03S',
      fontFamilyCN: '方正魏碑简体',
      url: 'https://s3.com/fonts/FZWBJW.ttf',
    },
    {
      fontFamily: ' FZTeCuGuangHuiS-R-GB',
      fontFamilyCN: '方正特粗光辉简体',
      url: 'https://s3.com/fonts/FZTCGHJW.ttf',
    },
    {
      fontFamily: 'FZSuXinShiLiuKaiS-R-GB',
      fontFamilyCN: '方正苏新诗柳楷简体',
      url: 'https://s3.com/fonts/FZSXSLKJW.ttf',
    },
    {
      fontFamily: 'FZShuSong-Z01S',
      fontFamilyCN: '方正书宋简体',
      url: 'https://s3.com/fonts/FZSSJW.ttf',
    },
    {
      fontFamily: 'FZShaoEr-M11S',
      fontFamilyCN: '方正少儿简体',
      url: 'https://s3.com/fonts/FZSEJW.ttf',
    },
    {
      fontFamily: 'FZPangWa-M18S',
      fontFamilyCN: '方正胖娃简体',
      url: 'https://s3.com/fonts/FZPWJW.ttf',
    },
    {
      fontFamily: 'FZPingHe-S11S',
      fontFamilyCN: '方正平和简体',
      url: 'https://s3.com/fonts/FZPHTJW.ttf',
    },
    {
      fontFamily: 'FZMiaoWuS-GB',
      fontFamilyCN: '方正喵呜体',
      url: 'https://s3.com/fonts/FZMWFont.ttf',
    },
    {
      fontFamily: 'FZMeiHei-M07S',
      fontFamilyCN: '方正美黑简体',
      url: 'https://s3.com/fonts/FZMHJW.ttf',
    },
    {
      fontFamily: ' FZLiuXingTi-M26S',
      fontFamilyCN: '方正流行体简体',
      url: 'https://s3.com/fonts/FZLXTJW.ttf',
    },
    {
      fontFamily: ' FZLanTingHeiS-EL-GB',
      fontFamilyCN: '方正兰亭纤黑简体',
      url: 'https://s3.com/fonts/FZLTXHJW.ttf',
    },
    {
      fontFamily: 'FZLanTingHeiS-HN-GB',
      fontFamilyCN: '方正兰亭特黑长简体',
      url: 'https://s3.com/fonts/FZLTTHCJW.ttf',
    },
    {
      fontFamily: 'FZLanTingHeiS-R-GB',
      fontFamilyCN: '方正兰亭黑简体',
      url: 'https://s3.com/fonts/FZLTHJW.ttf',
    },
    {
      fontFamily: 'FZLiBian-S02S',
      fontFamilyCN: '方正隶变简体',
      url: 'https://s3.com/fonts/FZLBJW.ttf',
    },
    {
      fontFamily: 'FZKai-Z03S',
      fontFamilyCN: '方正楷体简体',
      url: 'https://s3.com/fonts/FZKTJW.ttf',
    },
    {
      fontFamily: 'FZJianZhi-M23S',
      fontFamilyCN: '方正剪纸简体',
      url: 'https://s3.com/fonts/FZJZJW.ttf',
    },
    {
      fontFamily: 'FZJingLeiS-R-GB',
      fontFamilyCN: '方正静蕾简体',
      url: 'https://s3.com/fonts/FZJLJW.ttf',
    },
    {
      fontFamily: 'FZHanZhenGuangBiaoS-GB',
      fontFamilyCN: '方正汉真广标简体',
      url: 'https://s3.com/fonts/FZHZGBJW.ttf',
    },
    {
      fontFamily: 'FZHei-B01S',
      fontFamilyCN: '方正黑体简体',
      url: 'https://s3.com/fonts/FZHTJW.ttf',
    },
    {
      fontFamily: 'FZHanJianS-R-GB',
      fontFamilyCN: '方正汉简简体',
      url: 'https://s3.com/fonts/FZHJJW.ttf',
    },
    {
      fontFamily: 'FZHuangCao-S09S',
      fontFamilyCN: '方正黄草简体',
      url: 'https://s3.com/fonts/FZHCJW.ttf',
    },
    {
      fontFamily: 'FZGuLi-S12S',
      fontFamilyCN: '方正古隶简体',
      url: 'https://s3.com/fonts/FZGLJW.ttf',
    },
    {
      fontFamily: 'FZFangSong-Z02S',
      fontFamilyCN: '方正仿宋简体',
      url: 'https://s6.com/fonts/FZFSJW.TTF',
    },
    {
      fontFamily: 'FZDaHei-B02S',
      fontFamilyCN: '方正大黑简体',
      url: 'https://s3.com/fonts/FZDHTJW.ttf',
    },
    {
      fontFamily: 'FZDaBiaoSong-B06S',
      fontFamilyCN: '方正大标宋简体',
      url: 'https://s3.com/fonts/FZDBSJW.ttf',
    },
    {
      fontFamily: 'FZYaSongS-BN-GB',
      fontFamilyCN: '方正粗雅宋长简体',
      url: 'https://s3.com/fonts/FZCYSCJW.ttf',
    },
    {
      fontFamily: 'FZCuSong-B09S',
      fontFamilyCN: '方正粗宋简体',
      url: 'https://s3.com/fonts/FZCSJW.ttf',
    },
    {
      fontFamily: 'FZCuQian-M17S',
      fontFamilyCN: '方正粗倩简体',
      url: 'https://s3.com/fonts/FZCQJW.ttf',
    },
    {
      fontFamily: 'FZCuHuoYi-M25S',
      fontFamilyCN: '方正粗活意简体',
      url: 'https://s3.com/fonts/FZCHYJW.ttf',
    },
    {
      fontFamily: 'FZChaoCuHei-M10S',
      fontFamilyCN: '方正超粗黑简体',
      url: 'https://s3.com/fonts/FZCCHJW.ttf',
    },
    {
      fontFamily: 'FZBoYaSongS-GB',
      fontFamilyCN: '方正博雅宋简体',
      url: 'https://s3.com/fonts/FZBYSJW.ttf',
    },
    {
      fontFamily: 'FZZJ-YGYTKJW',
      fontFamilyCN: '方正字迹-叶根友特楷简体',
      url: 'https://s3.com/fonts/方正字迹-叶根友特楷简体.ttf',
    },
    {
      fontFamily: 'FZYanSongS-EB-GB',
      fontFamilyCN: '方正颜宋简体_大',
      url: 'https://s3.com/fonts/方正颜宋简体_大.ttf',
    },
    {
      fontFamily: 'FZRuiShuiYunS-EB-GB',
      fontFamilyCN: '方正锐水云简体_大',
      url: 'https://s3.com/fonts/方正锐水云简体_大.ttf',
    },
    {
      fontFamily: 'FZQiDiS-R-GB',
      fontFamilyCN: '方正启笛简体',
      url: 'https://s3.com/fonts/方正启笛简体.TTF',
    },
    {
      fontFamily: 'FZPinShangHeiS-B-GB',
      fontFamilyCN: '方正品尚粗黑简体',
      url: 'https://s3.com/fonts/方正品尚粗黑简体.TTF',
    },
    {
      fontFamily: 'FZLanTingYuanS-EB-GB',
      fontFamilyCN: '方正兰亭圆简体_大',
      url: 'https://s3.com/fonts/方正兰亭圆简体_大.ttf',
    },
    {
      fontFamily: 'FZGongYHS-R-GB',
      fontFamilyCN: '方正工业黑简体',
      url: 'https://s3.com/fonts/方正工业黑简体.TTF',
    },
    {
      fontFamily: 'FZTanHeiS-B-GB',
      fontFamilyCN: '方正粗谭黑简体',
      url: 'https://s3.com/fonts/方正粗谭黑简体.TTF',
    },
    {
      fontFamily: 'FZCuHeiSongS-B-GB',
      fontFamilyCN: '方正粗黑宋简体',
      url: 'https://s3.com/fonts/方正粗黑宋简体.TTF',
    },
    {
      fontFamily: 'FZBangShuXingS-R-GB',
      fontFamilyCN: '方正榜书行简体',
      url: 'https://s3.com/fonts/方正榜书行简体.TTF',
    },
    {
      fontFamily: 'HYBaiQingJ',
      fontFamilyCN: '汉仪柏青体',
      url: 'https://s3.com/fonts/HYBaiQingTiJ.ttf',
    },
    {
      fontFamily: 'HYBoJingTiJ',
      fontFamilyCN: '汉仪柏京体',
      url: 'https://s3.com/fonts/HYBoJingTiJ.ttf',
    },
    {
      fontFamily: 'HYCaiDieJ',
      fontFamilyCN: '汉仪彩蝶体',
      url: 'https://s3.com/fonts/HYCaiDieTiJ.ttf',
    },
    {
      fontFamily: 'HYBaiQiJ',
      fontFamilyCN: '汉仪白棋体',
      url: 'https://s3.com/fonts/HYBaiQiTiJ.ttf',
    },
    {
      fontFamily: 'HYCaiYunJ',
      fontFamilyCN: '汉仪彩云体',
      url: 'https://s3.com/fonts/HYCaiYunTiJ.ttf',
    },
    {
      fontFamily: 'HYDianYaTiJ',
      fontFamilyCN: '汉仪典雅体',
      url: 'https://s3.com/fonts/HYDianYaTiJ.ttf',
    },
    {
      fontFamily: 'HYDaiYuJ',
      fontFamilyCN: '汉仪黛玉体',
      url: 'https://s3.com/fonts/HYDaiYuTiJ.ttf',
    },
    {
      fontFamily: 'HYDaShengTiJ',
      fontFamilyCN: '汉仪大圣体',
      url: 'https://s3.com/fonts/HYDaShengTiJ.ttf',
    },
    {
      fontFamily: 'HYChangYiJ',
      fontFamilyCN: '汉仪长艺体',
      url: 'https://s3.com/fonts/HYChangYiTiJ.ttf',
    },
    {
      fontFamily: 'HYChenPinJ',
      fontFamilyCN: '汉仪陈频破体',
      url: 'https://s3.com/fonts/HYChenPinPoTiJ.ttf',
    },
    {
      fontFamily: 'HYHaHaJ',
      fontFamilyCN: '汉仪哈哈体',
      url: 'https://s3.com/fonts/HYHaHaTiJ.ttf',
    },
    {
      fontFamily: 'HYGanLanJ',
      fontFamilyCN: '汉仪橄榄体',
      url: 'https://s3.com/fonts/HYGanLanTiJ.ttf',
    },
    {
      fontFamily: 'HYGangYiTi,HYGangYiTi-85J',
      fontFamilyCN: '汉仪刚艺体',
      url: 'https://s3.com/fonts/HYGangYiTi-85J.ttf',
    },
    {
      fontFamily: 'HYFangDieJ',
      fontFamilyCN: '汉仪方叠体',
      url: 'https://s3.com/fonts/HYFangDieTiJ.ttf',
    },
    {
      fontFamily: 'HYDuDuJ',
      fontFamilyCN: '汉仪嘟嘟体',
      url: 'https://s3.com/fonts/HYDuDuTiJ.ttf',
    },
    {
      fontFamily: 'HYDieYuJ',
      fontFamilyCN: '汉仪蝶语体',
      url: 'https://s3.com/fonts/HYDieYuTiJ.ttf',
    },
    {
      fontFamily: 'HYHuaDieJ',
      fontFamilyCN: '汉仪花蝶体',
      url: 'https://s3.com/fonts/HYHuaDieTiJ.ttf',
    },
    {
      fontFamily: 'HYHeiQiJ',
      fontFamilyCN: '汉仪黑棋体',
      url: 'https://s3.com/fonts/HYHeiQiTiJ.ttf',
    },
    {
      fontFamily: 'HYHeiMiJ',
      fontFamilyCN: '汉仪黑咪体',
      url: 'https://s3.com/fonts/HYHeiMiTiJ.ttf',
    },
    {
      fontFamily: 'HYHeiLiZhiTiJ',
      fontFamilyCN: '汉仪黑荔枝体',
      url: 'https://s3.com/fonts/HYHeiLiZhiTiJ.ttf',
    },
    {
      fontFamily: 'HYHanShiTiJ',
      fontFamilyCN: '汉仪寒石体',
      url: 'https://s3.com/fonts/HYHanShiTiJ.ttf',
    },
    {
      fontFamily: 'HYHaiWenJ',
      fontFamilyCN: '汉仪海纹体',
      url: 'https://s3.com/fonts/HYHaiWenTiJ.ttf',
    },
    {
      fontFamily: 'HYLeMiaoTiJ',
      fontFamilyCN: '汉仪乐喵体',
      url: 'https://s3.com/fonts/HYLeMiaoTiJ.ttf',
    },
    {
      fontFamily: 'HYJinKaiJ',
      fontFamilyCN: '汉仪劲楷',
      url: 'https://s3.com/fonts/HYJinKaiJ.ttf',
    },
    {
      fontFamily: 'HYJinChangTiJ',
      fontFamilyCN: '汉仪锦昌体',
      url: 'https://s3.com/fonts/HYJinChangTiJ.ttf',
    },
    {
      fontFamily: 'HYJiaShuJ',
      fontFamilyCN: '汉仪家书',
      url: 'https://s3.com/fonts/HYJiaShuJ.ttf',
    },
    {
      fontFamily: 'HYHuPoJ',
      fontFamilyCN: '汉仪琥珀体',
      url: 'https://s3.com/fonts/HYHuPoTiJ.ttf',
    },
    {
      fontFamily: 'HYHuoChaiJ',
      fontFamilyCN: '汉仪火柴体',
      url: 'https://s3.com/fonts/HYHuoChaiTiJ.ttf',
    },
    {
      fontFamily: 'HYLiZhengEnXiaoKaiJ',
      fontFamilyCN: '汉仪李政恩小楷',
      url: 'https://s3.com/fonts/HYLiZhengEnXiaoKaiJ.ttf',
    },
    {
      fontFamily: 'HYLiuZiHeiJ',
      fontFamilyCN: '汉仪六字黑',
      url: 'https://s3.com/fonts/HYLiuZiHeiJ.ttf',
    },
    {
      fontFamily: 'HYLingXinJ',
      fontFamilyCN: '汉仪菱心体',
      url: 'https://s3.com/fonts/HYLingXinTiJ.ttf',
    },
    {
      fontFamily: 'HYLingBoJ',
      fontFamilyCN: '汉仪凌波体',
      url: 'https://s3.com/fonts/HYLingBoTiJ.ttf',
    },
    {
      fontFamily: 'HYLiLiangHeiJ',
      fontFamilyCN: '汉仪力量黑',
      url: 'https://s3.com/fonts/HYLiLiangHeiJ.ttf',
    },
    {
      fontFamily: 'HYLiangPinXianJ',
      fontFamilyCN: '汉仪良品线',
      url: 'https://s3.com/fonts/HYLiangPinXianJ.ttf',
    },
    {
      fontFamily: 'HYQiHei,HYQiHei-80J',
      fontFamilyCN: '汉仪旗黑-80',
      url: 'https://s3.com/fonts/HYQiHei-80J.ttf',
    },
    {
      fontFamily: 'HYQiHei,HYQiHei-50J',
      fontFamilyCN: '汉仪旗黑-50',
      url: 'https://s3.com/fonts/HYQiHei-50J.ttf',
    },
    {
      fontFamily: 'HYMiMiJ',
      fontFamilyCN: '汉仪咪咪体',
      url: 'https://s3.com/fonts/HYMiMiTiJ.ttf',
    },
    {
      fontFamily: 'HYMiaoHunTiJ',
      fontFamilyCN: '汉仪喵魂体',
      url: 'https://s3.com/fonts/HYMiaoHunTiJ.ttf',
    },
    {
      fontFamily: 'HYManBuJ',
      fontFamilyCN: '汉仪漫步体',
      url: 'https://s3.com/fonts/HYManBuTiJ.ttf',
    },
    {
      fontFamily: 'HYLuoBoJ',
      fontFamilyCN: '汉仪萝卜体',
      url: 'https://s3.com/fonts/HYLuoBoTiJ.ttf',
    },
    {
      fontFamily: 'HYRuiYiSongJ',
      fontFamilyCN: '汉仪瑞意宋',
      url: 'https://s3.com/fonts/HYRuiYiSongJ.ttf',
    },
    {
      fontFamily: 'HYQuHeiJ',
      fontFamilyCN: '汉仪趣黑简',
      url: 'https://s3.com/fonts/HYQuHeiJ.ttf',
    },
    {
      fontFamily: 'HYQuanTangShiJ',
      fontFamilyCN: '汉仪全唐诗',
      url: 'https://s3.com/fonts/HYQuanTangShiJ.ttf',
    },
    {
      fontFamily: 'HYQingYunJ',
      fontFamilyCN: '汉仪清韵体',
      url: 'https://s3.com/fonts/HYQingYunTiJ.ttf',
    },
    {
      fontFamily: 'HYQingTing,HYQingTing-55J',
      fontFamilyCN: '汉仪清庭-55简 Regular',
      url: 'https://s3.com/fonts/HYQingTing-55J.ttf',
    },
    {
      fontFamily: 'HYShouJinShuJ',
      fontFamilyCN: '汉仪瘦金书',
      url: 'https://s3.com/fonts/HYShouJinShuJ.ttf',
    },
    {
      fontFamily: 'HYShiGuangTiJ',
      fontFamilyCN: '汉仪时光体',
      url: 'https://s3.com/fonts/HYShiGuangTiJ.ttf',
    },
    {
      fontFamily: 'HYShenGongJ',
      fontFamilyCN: '汉仪神工体',
      url: 'https://s3.com/fonts/HYShenGongTiJ.ttf',
    },
    {
      fontFamily: 'HYShangWeiShouShuJ',
      fontFamilyCN: '汉仪尚魏手书',
      url: 'https://s3.com/fonts/HYShangWeiShouShuJ.ttf',
    },
    {
      fontFamily: 'HYRunYuan,HYRunYuan-75J',
      fontFamilyCN: '汉仪润圆-75简',
      url: 'https://s3.com/fonts/HYRunYuan-75J.ttf',
    },
    {
      fontFamily: 'HYRunYuan,HYRunYuan-45J',
      fontFamilyCN: '汉仪润圆-45简',
      url: 'https://s3.com/fonts/HYRunYuan-45J.ttf',
    },
    {
      fontFamily: 'HYTaiJiJ',
      fontFamilyCN: '汉仪太极体',
      url: 'https://s3.com/fonts/HYTaiJiTiJ.ttf',
    },
    {
      fontFamily: 'HYShuYuanHeiJ',
      fontFamilyCN: '汉仪舒圆黑',
      url: 'https://s3.com/fonts/HYShuYuanHeiJ.ttf',
    },
    {
      fontFamily: 'HYShuiDiJ',
      fontFamilyCN: '汉仪水滴体',
      url: 'https://s3.com/fonts/HYShuiDiTiJ.ttf',
    },
    {
      fontFamily: 'HYShuiBoJ',
      fontFamilyCN: '汉仪水波体',
      url: 'https://s3.com/fonts/HYShuiBoTiJ.ttf',
    },
    {
      fontFamily: 'HYShuangXianJ',
      fontFamilyCN: '汉仪双线体',
      url: 'https://s3.com/fonts/HYShuangXianTiJ.ttf',
    },
    {
      fontFamily: 'HYShuaiXianTiJ',
      fontFamilyCN: '汉仪帅线体',
      url: 'https://s3.com/fonts/HYShuaiXianTiJ.ttf',
    },
    {
      fontFamily: 'HYXiaoMaiTiJ',
      fontFamilyCN: '汉仪小麦体',
      url: 'https://s3.com/fonts/HYXiaoMaiTiJ.ttf',
    },
    {
      fontFamily: 'HYXiaoBoZheZhiTiJ',
      fontFamilyCN: '汉仪晓波折纸体',
      url: 'https://s3.com/fonts/HYXiaoBoZheZhiTiJ.ttf',
    },
    {
      fontFamily: 'HYWaWaZhuanJ',
      fontFamilyCN: '汉仪娃娃篆',
      url: 'https://s3.com/fonts/HYWaWaZhuanJ.ttf',
    },
    {
      fontFamily: 'HYTieXianHei,HYTieXianHei-65J',
      fontFamilyCN: '汉仪铁线黑-65简',
      url: 'https://s3.com/fonts/HYTieXianHei-65J.ttf',
    },
    {
      fontFamily: ' HYTieXianHei,HYTieXianHei-35J',
      fontFamilyCN: '汉仪铁线黑-35简',
      url: 'https://s3.com/fonts/HYTieXianHei-35J.ttf',
    },
    {
      fontFamily: 'HYTiaoTiaoTiJ',
      fontFamilyCN: '汉仪跳跳体',
      url: 'https://s3.com/fonts/HYTiaoTiaoTiJ.ttf',
    },
    {
      fontFamily: 'HYXueFengJ',
      fontFamilyCN: '汉仪雪峰体',
      url: 'https://s3.com/fonts/HYXueFengTiJ.ttf',
    },
    {
      fontFamily: 'HYXiXiuTiJ',
      fontFamilyCN: '汉仪细秀体',
      url: 'https://s3.com/fonts/HYXiXiuTiJ.ttf',
    },
    {
      fontFamily: 'HYXiXingKaiJ',
      fontFamilyCN: '汉仪细行楷 ',
      url: 'https://s3.com/fonts/HYXiXingKaiJ.ttf',
    },
    {
      fontFamily: 'HYXiuYingJ',
      fontFamilyCN: '汉仪秀英体',
      url: 'https://s3.com/fonts/HYXiuYingTiJ.ttf',
    },
    {
      fontFamily: 'HYXinRenWenSongJ',
      fontFamilyCN: '汉仪新人文宋',
      url: 'https://s3.com/fonts/HYXinRenWenSongJ.ttf',
    },
    {
      fontFamily: 'HYXingShiJ',
      fontFamilyCN: '汉仪醒示体',
      url: 'https://s3.com/fonts/HYXingShiTiJ.ttf',
    },
    {
      fontFamily: 'HYYaYaJ',
      fontFamilyCN: '汉仪丫丫体',
      url: 'https://s3.com/fonts/HYYaYaTiJ.ttf',
    },
    {
      fontFamily: 'HYYanRuiMinXingKaiJ',
      fontFamilyCN: '汉仪阎锐敏行楷',
      url: 'https://s3.com/fonts/HYYanRuiMinXingKaiJ.ttf',
    },
    {
      fontFamily: 'HYYanLingJ',
      fontFamilyCN: '汉仪雁翎体',
      url: 'https://s3.com/fonts/HYYanLingTiJ.ttf',
    },
    {
      fontFamily: 'HYYanKaiJ',
      fontFamilyCN: '汉仪颜楷简',
      url: 'https://s3.com/fonts/HYYanKaiJ.ttf',
    },
    {
      fontFamily: 'HYYaKuHeiJ',
      fontFamilyCN: '汉仪雅酷黑简',
      url: 'https://s3.com/fonts/HYYaKuHeiJ.ttf',
    },
    {
      fontFamily: 'HYXueJunJ',
      fontFamilyCN: '汉仪雪君体',
      url: 'https://s3.com/fonts/HYXueJunTiJ.ttf',
    },
    {
      fontFamily: 'HYZhuJieJ',
      fontFamilyCN: '汉仪竹节体',
      url: 'https://s3.com/fonts/HYZhuJieTiJ.ttf',
    },
    {
      fontFamily: 'HYZhongKaiJ',
      fontFamilyCN: '汉仪中楷',
      url: 'https://s3.com/fonts/HYZhongKaiJ.ttf',
    },
    {
      fontFamily: 'HYYuanLongHei,HYYuanLongHei-35J',
      fontFamilyCN: '汉仪元隆黑',
      url: 'https://s3.com/fonts/HYYuanLongHei-35J.ttf',
    },
    {
      fontFamily: 'HYYuanDieJ',
      fontFamilyCN: '汉仪圆叠体',
      url: 'https://s3.com/fonts/HYYuanDieTiJ.ttf',
    },
    {
      fontFamily: 'HYYouRanTiJ',
      fontFamilyCN: '汉仪悠然体',
      url: 'https://s3.com/fonts/HYYouRanTiJ.ttf',
    },
    {
      fontFamily: 'HYYiSongJ',
      fontFamilyCN: '汉仪意宋简',
      url: 'https://s3.com/fonts/HYYiSongJ.ttf',
    },
    
    {
      fontFamily: 'HYZongYiJ',
      fontFamilyCN: '汉仪综艺体',
      url: 'https://s3.com/fonts/HYZongYiTiJ.ttf',
    },
    {
      fontFamily: 'HYZhuZiTongNianTiJ',
      fontFamilyCN: '汉仪铸字童年体',
      url: 'https://s3.com/fonts/HYZhuZiTongNianTiJ.ttf',
    },
    {
      fontFamily: 'HYZhuZiChaoRanTiJ',
      fontFamilyCN: '汉仪铸字超然体',
      url: 'https://s3.com/fonts/HYZhuZiChaoRanTiJ.ttf',
    },
    { fontFamily: 'HYDaiYuJ', logogram: 'HYr3gj' },
    { fontFamily: 'HYHeiQiJ', logogram: 'HYm6gj' },
    { fontFamily: 'HYHeiMiJ', logogram: 'HYm2gj' },
    { fontFamily: 'HYXueFengJ', logogram: 'HYo2gj' },
    { fontFamily: 'HYXueJunJ', logogram: 'HYi4gj' },
    { fontFamily: 'HYYanLingJ', logogram: 'HYf4gj' },
    { fontFamily: 'HYChenPinJ', logogram: 'HYf5gj' },
    { fontFamily: 'HYChangYiJ', logogram: 'HYb6gj' },
    {
      fontFamily: 'HYTieXianHei,HYTieXianHei-35J',
      logogram: 'HYTieXianHei-CEJ',
    },
    { fontFamily: 'HYXingShiJ', logogram: 'HYb5gj' },
    { fontFamily: 'HYLuoBoJ', logogram: 'HYy2gj' },
    { fontFamily: 'HYLingXinJ', logogram: 'HYk2gj' },
    { fontFamily: 'HYHuaDieJ', logogram: 'HYf9gj' },
    { fontFamily: 'HYZongYiJ', logogram: 'HYk1gj' },
    { fontFamily: 'HYZhuJieJ', logogram: 'HYq1gj' },
    { fontFamily: 'HYXiuYingJ', logogram: 'HYy1gj' },
    { fontFamily: 'HYShenGongJ', logogram: 'HYh2gj' },
    { fontFamily: 'HYBaiQiJ', logogram: 'HYm5gj' },
    { fontFamily: 'HYShouJinShuJ', logogram: 'HYi3gj' },
    { fontFamily: 'HYHuPoJ', logogram: 'HYo1gj' },
    { fontFamily: 'HYHuoChaiJ', logogram: 'HYq2gj' },
    { fontFamily: 'HYManBuJ', logogram: 'HYr2gj' },
    { fontFamily: 'HYQingYunJ', logogram: 'HYg4gj' },
    {
      fontFamily: 'HYQingTing,HYQingTing-55J',
      logogram: 'HYQingTing-EEJ',
    },
    { fontFamily: 'HYRunYuan,HYRunYuan-45J', logogram: 'HYRunYuan-DEW' },
    { fontFamily: 'HYHaiWenJ', logogram: 'HYg5gj' },
    { fontFamily: 'HYShuiDiJ', logogram: 'HYp1gj' },
    { fontFamily: 'HYShuiBoJ', logogram: 'HYm7gj' },
    { fontFamily: 'HYGanLanJ', logogram: 'HYx1gj' },
    { fontFamily: 'HYBaiQingJ', logogram: 'HYj4gj' },
    { fontFamily: 'HYQiHei,HYQiHei-50J', logogram: 'HYQiHei-EZS' },
    { fontFamily: 'HYFangDieJ', logogram: 'HYb4gj' },
    { fontFamily: 'HYCaiDieJ', logogram: 'HYk5gj' },
    { fontFamily: 'HYCaiYunJ', logogram: 'HYl1gj' },
    { fontFamily: 'HYJiaShuJ', logogram: 'HYd2gj' },
    { fontFamily: 'HYWaWaZhuanJ', logogram: 'HYj2gj' },
    { fontFamily: 'HYTaiJiJ', logogram: 'HYo3gj' },
    { fontFamily: 'HYYuanDieJ', logogram: 'HYb8gj' },
    { fontFamily: 'HYDuDuJ', logogram: 'HYy4gj' },
    { fontFamily: 'HYHaHaJ', logogram: 'HYm4gj' },
    { fontFamily: 'HYMiMiJ', logogram: 'HYm1gj' },
    { fontFamily: 'HYShuangXianJ', logogram: 'HYb7gj' },
    {
      fontFamily: 'HYGangYiTi,HYGangYiTi-85J',
      logogram: 'HYGangYiTi-IEW',
    },
    { fontFamily: 'HYLingBoJ', logogram: 'HYr1gj' },
    {
      fontFamily: 'HYYuanLongHei,HYYuanLongHei-35J',
      logogram: 'HYYuanLongHei-CEJ',
    },
    { fontFamily: 'HYZhongKaiJ', logogram: 'HYc3gj' },
    { fontFamily: 'HYYaYaJ', logogram: 'HYg3gj' },
    { fontFamily: 'FZZhengHeiS-EB-GB', logogram: 'FZZDHJW--GB1-0' },
    { fontFamily: 'FZYanSongS-EB-GB', logogram: 'FZYANS_DAJW--GB1-0' },
    {
      fontFamily: 'FZRuiShuiYunS-EB-GB',
      logogram: 'FZRUISY_DAJW--GB1-0',
    },
    { fontFamily: 'FZQiDiS-R-GB', logogram: 'FZQDJW--GB1-0' },
    { fontFamily: 'FZPinShangHeiS-B-GB', logogram: 'FZPSCHJW--GB1-0' },
    {
      fontFamily: 'FZLanTingYuanS-EB-GB',
      logogram: 'FZLANTY_DAJW--GB1-0',
    },
    { fontFamily: 'FZLanTingKanHeiS-R-GB', logogram: 'FZLTKHJW--GB1-0' },
    { fontFamily: 'FZGongYHS-R-GB', logogram: 'FZGONGYHJW--GB1-0' },
    { fontFamily: 'FZTanHeiS-B-GB', logogram: 'FZCTHJW--GB1-0' },
    { fontFamily: 'FZCuHeiSongS-B-GB', logogram: 'FZCHSJW--GB1-0' },
    {
      fontFamily: 'FZBangShuXingS-R-GB',
      logogram: 'FZBANGSHUXINGJW--GB1-0',
    },
    { fontFamily: 'FZZongYi-M05S', logogram: 'FZZYJW--GB1-0' },
    { fontFamily: 'FZZhunYuan-M02S', logogram: 'FZY3JW--GB1-0' },
    { fontFamily: 'FZZhongDengXian-Z07S', logogram: 'FZZDXJW--GB1-0' },
    { fontFamily: 'FZZhiYi-M12S', logogram: 'FZZHYJW--GB1-0' },
    { fontFamily: 'FZZhanBiHei-M22S', logogram: 'FZZBHJW--GB1-0' },
    { fontFamily: 'FZYunDongHeiS-M-GB', logogram: 'FZYDZHJW--GB1-0' },
    { fontFamily: 'FZYouXian-Z09S', logogram: 'FZYXJW--GB1-0' },
    { fontFamily: 'FZYiHei-M20S', logogram: 'FZYHJW--GB1-0' },
    { fontFamily: 'FZXiaoZhuanTi-S13T', logogram: 'FZXZTFW--GB1-0' },
    { fontFamily: 'FZXiaoBiaoSong-B05S', logogram: 'FZXBSJW--GB1-0' },
    { fontFamily: 'FZXiQian-M15S', logogram: 'FZXQJW--GB1-0' },
    { fontFamily: 'FZXiHeiI-Z08S', logogram: 'FZXH1JW--GB1-0' },
    { fontFamily: 'FZXiDengXian-Z06S', logogram: 'FZXDXJW--GB1-0' },
    { fontFamily: 'FZWeiBei-S03S', logogram: 'FZWBJW--GB1-0' },
    { fontFamily: 'FZTeCuGuangHuiS-R-GB', logogram: 'FZTCGHJW--GB1-0' },
    {
      fontFamily: 'FZSuXinShiLiuKaiS-R-GB',
      logogram: 'FZSXSLKJW--GB1-0',
    },
    { fontFamily: 'FZShuSong-Z01S', logogram: 'FZSSJW--GB1-0' },
    { fontFamily: 'FZShaoEr-M11S', logogram: 'FZSEJW--GB1-0' },
    { fontFamily: 'FZPingHe-S11S', logogram: 'FZPHTJW--GB1-0' },
    { fontFamily: 'FZPangWa-M18S', logogram: 'FZPWJW--GB1-0' },
    { fontFamily: 'FZMiaoWuS-GB', logogram: 'FZMWJW--GB1-0' },
    { fontFamily: 'FZMeiHei-M07S', logogram: 'FZMHJW--GB1-0' },
    { fontFamily: 'FZLiuXingTi-M26S', logogram: 'FZLXTJW--GB1-0' },
    { fontFamily: 'FZLiBian-S02S', logogram: 'FZLBJW--GB1-0' },
    { fontFamily: 'FZLanTingHeiS-EL-GB', logogram: 'FZLTXHJW--GB1-0' },
    { fontFamily: 'FZLanTingHeiS-HN-GB', logogram: 'FZLTTHCJW--GB1-0' },
    { fontFamily: 'FZLanTingHeiS-R-GB', logogram: 'FZLTHJW--GB1-0' },
    { fontFamily: 'FZKai-Z03S', logogram: 'FZKTJW--GB1-0' },
    { fontFamily: 'FZJingLeiS-R-GB', logogram: 'FZJLJW--GB1-0' },
    { fontFamily: 'FZJianZhi-M23S', logogram: 'FZJZJW--GB1-0' },
    { fontFamily: 'FZHuangCao-S09S', logogram: 'FZHCJW--GB1-0' },
    { fontFamily: 'FZHei-B01S', logogram: 'FZHTJW--GB1-0' },
    { fontFamily: 'FZHanZhenGuangBiaoS-GB', logogram: 'FZHZGBJW--GB1-0' },
    { fontFamily: 'FZHanJianS-R-GB', logogram: 'FZHJJW--GB1-0' },
    { fontFamily: 'FZGuLi-S12S', logogram: 'FZGLJW--GB1-0' },
    { fontFamily: 'FZFangSong-Z02S', logogram: 'FZFSJW--GB1-0' },
    { fontFamily: 'FZDaHei-B02S', logogram: 'FZDHTJW--GB1-0' },
    { fontFamily: 'FZDaBiaoSong-B06S', logogram: 'FZDBSJW--GB1-0' },
    { fontFamily: 'FZCuYuan-M03S', logogram: 'FZY4JW--GB1-0' },
    { fontFamily: 'FZYaSongS-BN-GB', logogram: 'FZCYSCJW--GB1-0' },
    { fontFamily: 'FZCuSong-B09S', logogram: 'FZCSJW--GB1-0' },
    { fontFamily: 'FZCuQian-M17S', logogram: 'FZCQJW--GB1-0' },
    { fontFamily: 'FZCuHuoYi-M25S', logogram: 'FZCHYJW--GB1-0' },
    { fontFamily: 'FZChaoCuHei-M10S', logogram: 'FZCCHJW--GB1-0' },
    { fontFamily: 'FZBoYaSongS-GB', logogram: 'FZBYSJW--GB1-0' },
  ]
  